# Generated by Django 5.0.3 on 2024-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Playlist_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('Song_name', models.CharField(max_length=100)),
                ('Singer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
