# Generated by Django 5.0.3 on 2024-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arijit_Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents')),
                ('song', models.FileField(upload_to='documents')),
            ],
        ),
    ]
